name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-2022

    env:
      VCPKG_ROOT: './vcpkg'
      BUILD_TYPE: 'Release'
      VCPKG_BINARY_SOURCES: 'clear;nuget,GitHub,readwrite'

    steps:
    - uses: actions/checkout@v2

    - uses: actions/checkout@v2
      with:
        repository: 'microsoft/vcpkg'
        path: 'vcpkg'

    - uses: seanmiddleditch/gha-setup-ninja@master
    - uses: ilammy/msvc-dev-cmd@v1
    
    - name: 'Setup vcpkg'
      run: ./vcpkg/bootstrap-vcpkg.bat
    
    - name: 'Setup NuGet Credentials'
      shell: 'bash'
      run: >
        `./vcpkg/vcpkg fetch nuget | tail -n 1`
        sources add
        -source "https://nuget.pkg.github.com/BupTy03/index.json"
        -storepasswordincleartext
        -name "GitHub"
        -username "BupTy03"
        -password "${{ secrets.GITHUB_TOKEN }}"

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
